### PR TITLE
Include the mirror function

### PR DESCRIPTION
**Pull request by dwaardenburg**

### CODE REVIEW

**Comment by dwaardenburg** [comment]
Hope this will work then :D

**Comment by heitzmann** [comment]
Looks good, thanks again!

**Comment by amccaugh** [comment]
@dwaardenburg  @heitzmann Thoughts on setting the default arguments so that it's 
```
    def mirror(self, p1, p2 = (0,0)):
```

This would allow users to do e.g simple x-axis reflections by doing

```
mirror( (0, 1) )
```

without any loss of generality

**Comment by heitzmann** [comment]
Sounds good to me.

**Pull request merged**
