### PR TITLE
Master

### PR DESCRIPTION
**Pull request by amccaugh**
Updated the Polyon.fillet() function to allow a specifying fillet radius on a per-point basis.  This update is transparent and will not affect existing code.

gdspy.Polygon.fillet() now accepts either a number or a list for its radius argument.  If a list, len(radius) must equal the number of points in the Polygon so that every corner has its fillet radius specified (radius can be equal to zero to avoid filleting a point)

### CODE REVIEW

**Comment by amccaugh** [comment]
```
import gdspy
import numpy as np

gdspy.Cell.cell_dict.clear()
poly_cell = gdspy.Cell('POLYGONS')
x = [0,0,1,2]
y = [0,1,1,0]
xy = zip(x,y)
poly1 = gdspy.Polygon(xy, 1)

poly1.fillet([0.2, 0.05, 0.8, 0])

poly_cell.add(poly1)
gdspy.LayoutViewer()
```

Produces:

2016-07-17 18_01_01-settings

**Comment by heitzmann** [comment]
Thanks for the implementation @amccaugh! That's a great idea!
Wouldn't it be better to extend (by repeating) the list of radii when the polygon has more point than the list (similar to what is done for `layer` in `Path.segment`, for example)?

**Comment by amccaugh** [comment]
Personally I think it's better to be explicit in this case -- I think it's less likely than in the layer scenario that the user will want to have a repeating list of fillet radii than they will have be off in the length of the list (e.g. list has one more or one fewer element).  If the list is repeated it might hide the error from the user, which could be very bad but hard to notice (especially on large CAD layouts).   I know at least my from my own bad habits, I like it when I'm told directly that I didn't give the right inputs.  Thoughts?

**Comment by heitzmann** [comment]
Makes sense, I agree that this sort of error would be hard to notice from the user perspective. I'll merge it as is.

**Pull request merged**
