### PR TITLE
Improvements to to_gds() and Cell.copy() methods.

### PR DESCRIPTION
**Pull request by okianus**
The proposed changes include the following:

1. Performance improvement in object conversion to GDS (to_gds methods) for layouts with a large number of polygons.
2. Enhancement to Cell.copy() method to include / exclude specified layers in the copied cell.

The changes were implemented in Python 3.4, which is a requirement for our chip design workflow.

### CODE REVIEW

**Comment by heitzmann** [comment]
At some point we'll probably drop python 2 support, but I believe there are many users who still need it (specially considering python 2 is still the default in some OSes).
So, I'll try to filter only the core changes and skip the ones introduced by 2to3, but it will probably take some time.
Thanks for the contribution!

**Comment by rosivda** [comment]
Having worked exclusively with Python 3.4 version of gdspy, the current approach to keep Python 2 as the base branch appears to pose a challenge for us: should we now build on top of @okianus Python 3.4 performance enhancing branch? In the event of a new gdspy release, is the best way to rebase our version onto its 2to3 converted version? Has there been a new release scheduled in the next 6 months or so? If possible, please advise on the long-term strategy. Thanks.

**Comment by heitzmann** [comment]
Ideally I would like to keep both versions alive, so it's better if you worked on the python 2 codebase to avoid these conflicts.
I don't have a fixed release schedule. As soon as a new feature becomes stable I usually release a new version. The improvements here could be a new release as soon as we are able to merge them in version 2.

**Comment by heitzmann** [comment]
I've gone ahead and manually introduced you changes relative to polygon serialization into master.
I did not include the new `Cell.copy` method with `layers_to_include` and `layers_to_exclude`. The issue there is the following: some tools use datatypes instead of layers for process identification and others use a combination of both datatype and layer. So it's preferable to keep a symmetry in the treatment of those properties (that means having a `datatypes_to_include` and `datatypes_to_exclude` at least).

How do we deal with intersections? For example, if `layers_to_include = [1,2]` and `datatypes_to_exclude = [1]`, how do we deal with elements in layer/datatype 1/1 and 3/0?

Can we think of other argument names to make this specification less confusing?

**Pull request closed without merging**
