### PR TITLE
adding CICD

### PR DESCRIPTION
**Pull request by joamatab**
adding CI/CD to test in different python versions on every push as well as daily

### CODE REVIEW

**Comment by heitzmann** [comment]
Sorry for my ignorance, but hownis this different from the existing Travis and Appveyor integrations?

**Comment by joamatab** [comment]
Hi Lucas, 

i find easier to see the status of the build with Github actions,

im not sure how to look your travis CI/CD but here you can see if CI/CD passes daily, on push or on pull request

**Comment by heitzmann** [comment]
The README shields for "building" are buttons for Travis and Appveyor. If you click them you see the build logs. They are already tested on every push and automatically generate the Windows pre-compiled binaries on releases.

All being the same, I'll stick with the system already in place.

**Comment by heitzmann** [comment]
Hi @joamatab, just a follow-up. Ironically, Travis-CI stopped working mid June (I believe they changed .org to .com and we had to manually update the webhook). Since I'd have to update all the configs and authorizations in the repository, I decided to move to Github Actions for testing on Linux and OSX. For Windows I'll keep using AppVeyor because it automates the binary release.

**Comment by joamatab** [comment]
Hi Lucas,

interesting :)

feel free to use any of the github actions I use
https://github.com/gdsfactory/gdsfactory/tree/master/.github/workflows

thank you for your work with gdspy, it's an amazing tool

**Pull request closed without merging**
