### PR TITLE
speed improvement in remove_polygons

### PR DESCRIPTION
**Pull request by tvt173**
Removal of an item from a list at an arbitrary index in python is an O(N) operation. Repeatedly doing this over a list can be very costly, as is done in the current `remove_polygons()` function. This MR instead filters the existing list into a new list via a list comprehension, which is much faster in scenarios where there are many polygons to remove.

### CODE REVIEW

**Comment by heitzmann** [comment]
Looks good, thanks!

**Comment by tvt173** [comment]
thanks @heitzmann! looking forward to the next release with this patch. i see orders of magnitude speed improvement in development

**Comment by tvt173** [comment]
hi @heitzmann , would it be possible to get a new release with this patch?

**Comment by heitzmann** [comment]
Sure!

**Comment by tvt173** [comment]
thanks Lucas! -- obrigado

**Pull request merged**
