### PR TITLE
High-performance “points inside a set of polygons” logical test

### PR DESCRIPTION
**Pull request by okianus**
This pull request adds the functionality of high-performance “points inside a set of polygons” logical test: given a set of points and a set of polygons, the test returns a boolean list indicating whether each of the given points is inside or outside the set of polygons. Note that clipper.cpp currently contains a `PointInPolygon()` function. The new `inside()` function makes use of `PointInPolygon` to deal with very large datasets to achieve optimal performance. 

`inside()` allows for logical grouping of the given points to enable short-circuit logical test (if the logic is true for one member of a group, it is true for the entire group). The algorithm has been used on large datasets containing more than 800,000 points and 2,000 polygons with execution time on the order of 10 seconds.

Within `__init__.py`, there are two modifications:
1.	A new method `inside()`
2.	A minor modification to the `Cell.copy()` method: deep copy of `elements` and `labels` (required for copying of `Cell` objects with hierarchical structure)

Within clipper.cpp, there are three modifications:
1.	A new function `inside()`
2.	A new helper function `BoundingBox()`
3.	Related documentation

No other files are affected.

### CODE REVIEW

**Comment by rosivda** [comment]
I would like to provide additional info with regard to this pull request. Our use of @okianus ’s fork with the proposed c-extension has sped up our ability to assemble large chips by a factor of 250 (from about a day to minutes). Also, in many applications, the use of groupsize and groupstate options provides a much faster alternative to the polygon overlap test using gdspy.boolean. Of note here is that while gdspy.boolean provides mathematically rigorous check for the overlapping shapes, the inside() facility is less general as it would not detect cases when overlapping shapes do not contain any points inside each other. This limitation, however, has not been found to limit our ability to use it.
To the best of my understanding, the inside() function is the only remaining difference between the @okianus  and @heitzmann versions of gdspy. As such, this pull request presents us with a fantastic opportunity to merge the two versions together back under @heitzmann maintenance.

**Comment by okianus** [comment]
Yes, this is to confirm that currently the only difference between the fork and the main branch of gdspy is the inside() method (earlier modifications to the Cell.copy() method involving layers to include / exclude have been reverted). If this pull request is integrated, there will be no need to maintain a separate fork,  eliminating branch divergence.

**Comment by heitzmann** [comment]
Sounds good, I'll have to take a look at the code because of the python 2/3 differences, but I'll get to it asap.

**Comment by heitzmann** [comment]
I've included the changes in the master branch, but I'd like to propose a change in the function call. I understand that the reason for having `groupsize` is to short-circuit the test within each group, right? But that forces all groups to have the same size. What if we changed the call to accept points as an array of coordinates or groups (each group being an array of coordinates)? In that case each group could have any number of points. The result would be a boolean list with length equal to the number of groups.

The signature could be:
`inside(points, polygons, short_circuit='any', precision=0.001)`
with `short_circuit` meaning:
- `'any'`: returns `True` if any point in the group is inside one of the polygons
- `'all'`: returns `True` if all points in the group are inside one of the polygons

In the case with no groups (just a list of points), `short_circuit` is irrelevant and the return list contains the test result for each point.

What do you think?

**Comment by heitzmann** [comment]
Almost forgot: the modifications in `Cell.copy` were included with the addition of a keyword to maintain backwards compatibility.

**Comment by okianus** [comment]
@heitzmann, thank you for integrating the changes! Your proposed (and implemented!) changes should work perfectly for my use cases, and indeed will provide more flexibility for varying `groupsize`. I will test the latest commit tomorrow and provide some feedback.

**Comment by okianus** [comment]
@heitzmann, I have tested your latest commit with our use cases, and all work perfectly. I looked at both `any` and `all` options, but did not experiment with varying group sizes. 

In case you're interested, here's an example of one of the bigger test cases:
  - >1.4 million points, logically grouped into groups of 4
  - points are compared against ~2500 polygons with a total of ~125,000 vertices
  - using grouped data (i.e. with short-circuiting) vs a flat list of points (i.e. no short-circuiting) for the same data set improves the performance by more than 40%. 

Thank you for your quick action on this!

**Comment by heitzmann** [comment]
Good to hear everything worked. Those numbers are way beyond what we usually consider in academia! Very impressive...

I'm closing this PR without merging, since the changes are already there.

**Pull request closed without merging**
