### PR TITLE
Adds PROPATTR and PROPVALUE to cells

### PR DESCRIPTION
**Pull request by arthur00**
This patch adds the ability read in attribute tables in GDSII format (0x2B and 0x2C features) and saves them in a list of tuples on the Cell object.

This patch does not support writing them back to the GDSII file - this can be introduced later.

### CODE REVIEW

**Comment by heitzmann** [comment]
@arthur00 According to the [specification](http://boolean.klaasholwerda.nl/interface/bnf/gdsformat.html) I have, these records should belong to GDSII elements, not cells. Also, since all PROPATTR values for a given element must be different, I believe this would be better implemented as a dictionary, instead of a list of tuples.

I've started working on those for polygons, but support for paths, labels, and references is still missing. Please check out branch properties 889f0f2556d5114aafdc9b40cc55e8b7ce9a3d5f.

**Comment by arthur00** [comment]
@heitzmann  ahh, thank you for the clarification, I went through the spec and it seems you are right. In KLayout they have "user properties" on cells, and that is a lot more convenient since that's the level where I need add additional information. Would you consider supporting cell-level properties as well, at least for reading? This might be a bit tricky since you'll have to know whether the properties are applying to an element or a cell. But it would be tremendously helpful. If not, that's OK, I will fork off the existing branch and create our own "out-of-spec" version to suit our immediate needs.

As for the dictionary versus tuple - I saw that you used __slots__ to reduce the memory footprint of cells, so I figured you'd want to save memory. An empty dictionary takes 240 bytes, which seems a lot to me under these circumstances.

https://lerner.co.il/2019/05/12/python-dicts-and-memory-usage/

However, researching to make this point on this article, I just noticed that you can call clear() to reduce the dictionary size to 72. When I added an element to it, it went back to 240 though, whereas adding an element to a list increased it to 96.

```
>>> import sys
>>> a= []
>>> sys.getsizeof(a)
64
>>> b = {}
>>> sys.getsizeof(b)
240
>>> b.clear()
>>> sys.getsizeof(b)
72
>>> b['a'] = None
>>> b
{'a': None}
>>> sys.getsizeof(b)
240
>>> a.append(None)
>>> a
[None]
>>> sys.getsizeof(a)
96
>>> 
```

**Comment by heitzmann** [comment]
What version of python are you using. On 3.8 I get 64 bytes for an empty dictionary and 56 for the list. On 2.7 its 280 and 72, respectively, but I don't think we should bother with 2.x anymore for a decision such as this. Considering that it is only 8 bytes of difference, I believe dictionaries would be preferable, given the intention of the attribute, don't you think. At least to me it seems more intuitive.

Of course I'm only comparing the empty cases because that's what almost all users will see... in 10 years of Gdspy this is the first time I see anyone using these records.

As for the help, thank you for offering, but I'm already more than halfway through, so I believe it's fine.

**Comment by heitzmann** [comment]
@arthur00 I believe all property cases are handled in 13040e7e27aa32eb35d623d0fd82310cbdc9d8f1. Would you mind checking whether those changes work in your case? If so, I'll merge them into branch next.

**Comment by arthur00** [comment]
That's interesting, I am on Python 3.6.8 in Linux 64 bit. I agree that dictionaries are preferable - my first implementation was also dictionary. It was the __slots__ that made me think more memory-conservative. I'm ok either way, but keep in mind that others may have the same memory penalty I do. You should consider how many instances of Cells you want to support on your library and maximum footprint you are willing to spend to determine if it matters or not.

I agree that the empty case will be 99.99% of all cells. In which case the most efficient way is to store all props outside of the object, tied to the library itself. Each element won't have a reference to its properties, but you can get properties for an element by going to the library property dictionary. It all boils down to how much you care about memory footprint.

**Comment by arthur00** [comment]
> @arthur00 I believe all property cases are handled in [13040e7](https://github.com/heitzmann/gdspy/commit/13040e7e27aa32eb35d623d0fd82310cbdc9d8f1). Would you mind checking whether those changes work in your case? If so, I'll merge them into branch next.

Looks good to me!

**Comment by heitzmann** [comment]
The memory issue was really my firt motivation fpr creating gdspy, but to tie the props to the library seems weird to me. It is an invitation to bugs and unexpected results when copying, moving or duplicating cells and elements, don't you think?

Just as an observation: the number of cells should not be an issue with memory if one uses GdsWriter instead of GdsLibrary. The number of elements is, so the matter of adding a dict to each is indeed a problem.

Another solution is to initialize all properties to `None` instead of an empty dict. The user would be responsible for initialization. I don't really love this idea, because of extra the user requirement.

Alternatively, when memory is an issue, we could instruct the user to set properties to `None` in all elements (and support that when saving the gds).

Do you see any other solution?

**Comment by arthur00** [comment]
I agree - if you attached to the library you would need to make sure to update the dictionary every time copying, moving and duplicating happens. 

I like the last idea - if memory is an issue, you can instruct user to set properties to None. This creates a solution if memory ever becomes an issue, but until then, you'd be taking the optimistic approach that it won't be a problem. Which I think is true.

**Pull request closed without merging**
