### PR TITLE
Store parameters of 'Round' object upon creation

### PR DESCRIPTION
**Pull request by Aypac**
I'm working on a [GDS to Latex converter](https://github.com/Aypac/GDSLatexConverter) right now. TikZ (as opposed to GDS) supports the direct plotting of circles. In order to save resources, I would like to provide an option to directly access the parameters used to create circular structures. Thus this simple addition.

As far as I understand, this solution does not work when loading GDS files into gdspy, but I still believe that it is better than nothing. Please consider adopting this change.

### CODE REVIEW

**Comment by heitzmann** [comment]
This change creates unnecessary memory overhead, whereas Gdspy aims to be as memory efficient as possible to allow the user to create large layouts. (That, in fact, is the original reason why gdspy was created.)

More than that, the Round class is not only used for circles: regular polygons can be constructed by setting the desired number of vertices. Assuming that Round would be only used for circles overrides the user's choice, which I believe would be incorrect for your converter as well.

**Comment by Aypac** [comment]
Thank you very much for your reaction!

The memory overhead issue is of course valid. On the other hand, it is a VERY small overhead (it is 6 floats, which compares to having 3 additional points to the polygon, that do not end up in the created gds file).

For the second argument: I fully agree. Thus I would not do this by default, but just allow it as an option to save resources.

I can understand from your arguments however if you decide to not accept this pull request. (Please feel free to ignore the following part if you don't want to invest any more time on this) Our alternative path would be to investigate all polygons like this:

    For each polygon in a polygon set (with 2 or less polygons and more than x points per polygon):
      go over each polygon and calculate the distance between neighbouring points
      If they are all equal (enough):
         it is a circle
      elif they are all equal (enough), except for one:
         it is an arc
      else:
         ignore

(as outlined in this [issue](https://github.com/Aypac/GDSLatexConverter/issues/9))

Would you think this is a 'save/good' way to go about this (provided that the user can always turn this option off)?

**Comment by heitzmann** [comment]
I believe your algorithm would work most of the time, but there are edge cases that might throw it off, for example, in gdspy one could use Path.parametric to create a spiral with equally-spaced points that would be detected as an arc.

Take a look at [this question](https://stackoverflow.com/questions/9063830/whether-multiple-points-make-up-for-a-circle) and the algorithms suggested in the answers. There is some high level stuff that might be more computationally efficient.

**Comment by Aypac** [comment]
Okay, that sounds promising. Thank you very much!

**Pull request closed without merging**
