### PR TITLE
Use numpy for serializing polygons instead of for loop (large speedup)

### PR DESCRIPTION
**Pull request by fbeutel**
Don't use for loops when serializing polygons, but use numpy instead.

This gives a very large speedup for larger polygons. As an example, I ran the following test script. Results:
- Old version: 85.38 s
- New version: 0.17 s

```
import numpy as np
import gdspy
import time

def make_circle(x_offset, y_offset, n_points, multiplier=1000):
    p = np.linspace(0, 2*np.pi, n_points)
    x, y = x_offset + np.cos(p) * multiplier, y_offset + np.sin(p) * multiplier
    return np.transpose(np.vstack((x,y)))

lib = gdspy.GdsLibrary()
c1 = gdspy.Cell('test_cell', True)

for i in range(100):
    c1.add(gdspy.Polygon(make_circle(0, i*2000, 199)))
    c1.add(gdspy.Polygon(make_circle(2000, i*2000, 8000)))
    c1.add(gdspy.Polygon(make_circle(4000, i*2000, 20000)))
    
lib.add((c1))

start = time.time()
lib.write_gds('test.gds')
print("Time: {} s".format(time.time() - start))
```

### CODE REVIEW

**Comment by heitzmann** [comment]
Looks pretty good!
Have you tested using numpy serialization but without changing the string building from `.append` to `+=`? I ask because I was under the impression that adding strings is less efficient than appending to a list and then `join`-ing.

**Comment by heitzmann** [comment]
Here's what I mean:

```python
In [1]: def f(): 
   ...:     a = b'' 
   ...:     for i in range(100000): 
   ...:         a += str(i).encode('utf-8') 
   ...:     return a 
   ...:                                                                                       

In [2]: def g(): 
   ...:     a = [] 
   ...:     for i in range(100000): 
   ...:         a.append(str(i).encode('utf-8')) 
   ...:     return b''.join(a) 
   ...:                                                                                       

In [3]: %timeit f()                                                                           
1.56 s ± 126 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)

In [4]: %timeit g()                                                                           
37.7 ms ± 2.23 ms per loop (mean ± std. dev. of 7 runs, 10 loops each)
```

So, using numpy's serialization makes sense, but without the change to the string construction.

**Comment by fbeutel** [comment]
You are right. In my benchmark it didn't show any difference, because I don't work with polygon sets with many polygons, but of course in general that should be better...

**Comment by heitzmann** [comment]
I ended up manually including your changes in de49fef.

**Pull request closed without merging**
